language: rust

rust:
    - stable

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

addons:
    apt:
        packages:
            - portaudio19-dev

script:
    - cargo build
    - cargo test
    - cargo doc --no-deps
    - "rustdoc --test README.md -L target/debug -L target/debug/deps $(pkg-config --libs-only-L portaudio-2.0 | sed 's/-L/-Lnative=/')"

after_success:
    - curl https://mvdnes.github.io/rust-docs/travis-doc-upload.sh | bash
